// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.778
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Login() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<html><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Go Journal</title><!-- Tailwind CSS --><link href=\"https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css\" rel=\"stylesheet\"><script src=\"https://unpkg.com/htmx.org@1.9.2\"></script><style>\n        .fade-in {\n            opacity: 0;\n            transition: opacity 0.5s ease-in-out;\n        }\n        .fade-in.show {\n            opacity: 1;\n        }\n\t\t\t\t</style></head><title>Login</title><body><div class=\"h-screen flex items-start justify-center bg-gray-100 pt-20\"><div class=\"w-full max-w-sm p-6 bg-white rounded-lg shadow-md space-y-6\"><h1 class=\"text-2xl font-bold text-center\">My Journal</h1><form method=\"POST\" action=\"/login\" class=\"space-y-4\"><div><label class=\"block text-sm font-medium text-gray-700\">Username</label> <input type=\"text\" name=\"username\" required class=\"mt-1 block w-full p-2 border border-gray-300 rounded-md focus:ring-black focus:border-black\"></div><div><label class=\"block text-sm font-medium text-gray-700\">Password</label> <input type=\"password\" name=\"password\" required class=\"mt-1 block w-full p-2 border border-gray-300 rounded-md focus:ring-black focus:border-black\"></div><button type=\"submit\" class=\"w-full bg-black text-white font-semibold py-2 px-4 rounded hover:bg-gray-800 transition duration-300\">Login</button></form><div class=\"block text-sm font-medium text-gray-700\"><a href=\"/register\" class=\"text-black-500 hover:underline\">Create an account</a></div></div></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
